In [14]:
import numpy as np

In [15]:
# arange() :
#np.arange(star, End, steps)
a = np.arange(1,13)
b = np.arange(1,13,2)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]


In [16]:
# linspace()
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [22]:
# reshape()
x = np.arange(1,13)
y = x.reshape(2,6)
print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [23]:
# ravel()   conver 1D array
y.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
# flatten()
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
# transpose()
y.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])