In [1]:
import numpy as np

# Dimensions

In [19]:
arr1 = np.array([10,11,12,13,14,15])
print(arr1[2])
print("Dimensions:", arr1.ndim) 

12
Dimensions: 1


In [20]:
# 2D Array.
# np.array(arr[row,column])

arr2 = np.array([
    [12,13,14,15,16], 
    [22,23,24,25,26]
])

print(arr2[1, 3])
print("Dimensions:", arr2.ndim) 

25
Dimensions: 2


In [75]:
arr1 = np.arange(1,101).reshape(10,10)
print(arr1)
print("Dimensions:", arr1.ndim) 

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Dimensions: 2


In [77]:
# arr1[row1:row2 , col1:col2]
print(arr1[3:5 , 7:9])

[[38 39]
 [48 49]]


In [21]:
# 3D Array.
# np.array(arr[Block, row, column])

arr3 = np.array([
    [  # Block 0
        [12,13,14,15,16], 
        [17,18,19,20,21],
        [22,23,24,25,26]
    ]
])

print(arr3[0, 2, 2])
print("Dimensions:", arr3.ndim) 
print("Shape:", arr3.shape) 

24
Dimensions: 3
Shape: (1, 3, 5)


In [22]:
arr3 = np.array([
    [  # Block 0
        [11, 12, 13],   # Row 0
        [14, 15, 16],   # Row 1
        [17, 18, 19]    # Row 2
    ],
    [  # Block 1
        [21, 22, 23],   # Row 0
        [24, 25, 26],   # Row 1
        [27, 28, 29]    # Row 2
    ]
])
print(arr3[1, 2, 1])  
print("Dimensions:", arr3.ndim)
print("Shape:", arr3.shape) 

28
Dimensions: 3
Shape: (2, 3, 3)


In [25]:
# 4D Array
# np.array(arr[Block, row, column, elements])

arr_4d = np.array([
    [  # Block 0
        [[1, 2], [3, 4]],     # Row 0 (2 columns)
        [[5, 6], [7, 8]]      # Row 1 (2 columns)
    ],
    [  # Block 1
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

print(arr_4d[1, 0, 1, 0])
print("Dimensions:", arr_4d.ndim) 

11
Dimensions: 4


In [26]:
# 5D

arr5 = np.array([[[[[12,23,34,45,56,78,89]]]]])
print("Dimensions:", arr5.ndim) 

Dimensions: 5


# Array Calculation

In [31]:
# axis = 0 ---> Columns
# axis = 1 ---> Rows

arr2 = np.array([
    [12,13,14,15,16], 
    [22,23,24,25,26]
])

print(np.sum(arr2, axis=0)) # Columns.
print(np.sum(arr2, axis=1)) # Rows.

[34 36 38 40 42]
[ 70 120]


# Slicing

In [39]:
# 1D Array
# arr[start : end+1]

arr_1d = np.array([10, 20, 30, 40, 50, 60])
print(arr_1d[1:4])       
print(arr_1d[:3])        
print(arr_1d[-2:]) 
print(arr_1d[-3:])
print(arr_1d[::2])

[20 30 40]
[10 20 30]
[50 60]
[40 50 60]
[10 30 50]


In [43]:
# 2D Array Slicing
# arr[row, start:end+1]

arr_2d = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

print(arr_2d[1, :3])
print(arr_2d[2, 1:])

[21 22 23]
[32 33]


In [45]:
# 3D Array Slicing
# arr_3d[Block, row, start:end+1]

arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr_3d[1,1, :2])

[10 11]


# Shape

In [46]:
arr = np.array([
    [1,2,3,4],
    [1,2,3,4]
])
arr.shape

(2, 4)

In [48]:
arr = np.array([
    [
        [1,2,3,4], 
        [4,3,2,1], 
        [1,2,3,4]
    ]
])
arr.shape

(1, 3, 4)

# Joining Array

In [59]:
# 1D Array

arr = np.array([1, 2, 3, 4])
arr1 = np.array([5, 6, 7, 8])
arr2 = np.array([9, 10, 11, 12])
a = np.concatenate((arr, arr1, arr2))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [63]:
# 2D Array

arr = np.array([[1,2,3], [4,5,6]])
arr1 = np.array([[10,11,12], [13,14,15]])

arr2 = np.concatenate((arr, arr1), axis=1)
arr2

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

# Spliting Array

In [64]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

# ravel & flatten

## converts multidimensional array into 1D array

In [66]:
arr = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]]])
print(arr)
print("Dimension is", arr.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Dimension is 3


In [69]:
new = arr.ravel()
print(new)
print("Now the new dimension is" , new.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Now the new dimension is 1


In [70]:
new = arr.flatten()
print(new)
print("Now the new dimension is" , new.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Now the new dimension is 1


# Unique Function

In [71]:
arr = np.array([12,3,21,3,45,54,3,22,21,2,77,4,6,77,4])

x = np.unique(arr)
x

array([ 2,  3,  4,  6, 12, 21, 22, 45, 54, 77])

# Delete

In [72]:
arr = np.array([12,13,14,15])
d = np.delete(arr, [1])
d

array([12, 14, 15])

In [74]:
x = np.array([[1,2,3,4,5], [4,32,1,4,5], [6,7,8,9,10]])

y = np.delete(x, 1, axis=0)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])