In [4]:
import numpy as np
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [5]:
type(arr_1d)

numpy.ndarray

In [6]:
arr_1d.ndim

1

In [7]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_2d)
type(arr_2d)
arr_2d.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [8]:
arr_2d.size

10