In [1]:
import numpy as np

In [2]:
# bydefault float value printed.
m = np.ones((4,5))
print(m)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
# Avoid float value & You can add any datatype according your choice.
m = np.ones((3,4), dtype = int)
print(m)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
# Print 0 number in Array
n = np.zeros((3,4), dtype = int)
print(n)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
# print empty matrics in array
x = np.empty((3,4), dtype = int)
print(x)

[[          0           0        2272           0]
 [          0           0 -1424704080         656]
 [          0           0       65793           0]]
