In [1]:
import numpy as np
import random 

In [2]:
np.random.random(1) #Generate number between 0 to 1.

array([0.91179664])

In [3]:
np.random.random((3,3))

array([[0.31504039, 0.3190685 , 0.61479631],
       [0.77349938, 0.5000697 , 0.03330841],
       [0.51393017, 0.86015462, 0.12226339]])

In [4]:
np.random.randint(1,4) #To find integer value between 1 to 4

1

In [5]:
np.random.randint(1,4, (4,4))

array([[3, 1, 3, 2],
       [2, 3, 2, 2],
       [3, 2, 1, 1],
       [3, 1, 3, 1]])

In [6]:
np.random.randint(1,4, (2, 4,4))

array([[[1, 1, 1, 2],
        [1, 2, 3, 3],
        [1, 1, 2, 3],
        [2, 3, 1, 2]],

       [[1, 1, 1, 2],
        [3, 2, 2, 1],
        [3, 3, 1, 1],
        [1, 2, 3, 3]]])

In [7]:
np.random.rand(3)

array([0.41927636, 0.56550152, 0.97838348])

In [8]:
np.random.rand(3,3)

array([[0.41272065, 0.97439372, 0.39987199],
       [0.91238177, 0.57265308, 0.09676936],
       [0.31235812, 0.31104012, 0.91528295]])

In [9]:
np.random.randn(3,3) # To gives us negative and positive value.

array([[-0.62178809, -1.0628688 ,  2.4955796 ],
       [ 0.75090661, -1.37151714,  0.84143333],
       [-0.9475541 ,  0.35883838,  0.32850939]])

In [11]:
x = [1,2,3,4,5]
for i in range(20):
    print(np.random.choice(x))

3
1
4
1
4
4
2
2
1
1
4
5
5
5
2
5
2
1
2
1
